version: "3.8"

services:
  hydra-migrate:
    image: oryd/hydra:v2.0.0
    container_name: hydra-migrate
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
      - SECRETS_SYSTEM=${SECRETS_SYSTEM} # use env variable from .env
    entrypoint: /bin/sh -c "hydra migrate sql --yes && hydra serve all --dangerous-force-http"

  hydra:
    image: oryd/hydra:v2.0.0
    container_name: hydra
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
      - SECRETS_SYSTEM=${SECRETS_SYSTEM} # use env variable from .env
      - URLS_SELF_ISSUER=${HYDRA_PUBLIC_URL}
      - URLS_CONSENT=${HYDRA_CONSENT_URL}
      - URLS_LOGIN=${HYDRA_LOGIN_URL}
      - LOG_LEVEL=debug
    ports:
      - "4444:4444"
      - "4445:4445"
    depends_on:
      - postgres
    env_file:
      - .env # reference the .env file here

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
